enum LocalStorageItem {
  BEARER_TOKEN = 'BEARER_TOKEN',
  CURRENT_USER_ID = 'CURRENT_USER_ID',
  ICON_THEME = 'ICON_THEME',
  THEME = 'THEME',
  LANGUAGE = 'LANGUAGE',
  PROFILE_PICTURE = 'PROFILE_PICTURE',
  BOTTOM_TAB_BAR_HEIGHT = 'BOTTOM_TAB_BAR_HEIGHT',
}

export default LocalStorageItem;
