/*
    theme colors generated by https://callstack.github.io/react-native-paper/docs/guides/theming
    withs colors :
        export enum Color {
            PRIMARY = '#ED2272',
            SECONDARY = '#2F215F',
            TERTIARY =  '#7B5733',
            SUCCESS = '#23C766',
            ERROR = '#EF4B56',
        }
*/

import { AppTheme } from "#modules/core/style/themes/beans/theme";
import {
  borderRadius,
  spacers,
  tags,
} from "#modules/core/style/themes/beans/theme.utils";

export const darkPaperTheme: AppTheme = {
  colors: {
    primary: "rgb(255, 177, 194)",
    onPrimary: "rgb(102, 0, 43)",
    primaryContainer: "rgb(143, 0, 64)",
    onPrimaryContainer: "rgb(255, 217, 223)",
    secondary: "rgb(204, 190, 255)",
    onSecondary: "rgb(52, 31, 116)",
    secondaryContainer: "rgb(75, 56, 140)",
    onSecondaryContainer: "rgb(231, 222, 255)",
    tertiary: "rgb(236, 190, 145)",
    onTertiary: "rgb(70, 42, 9)",
    tertiaryContainer: "rgb(96, 64, 30)",
    onTertiaryContainer: "rgb(255, 220, 189)",
    error: "rgb(255, 179, 178)",
    onError: "rgb(104, 0, 19)",
    errorContainer: "rgb(146, 0, 31)",
    onErrorContainer: "rgb(255, 218, 217)",
    background: "rgb(32, 26, 27)",
    onBackground: "rgb(236, 224, 225)",
    surface: "rgb(32, 26, 27)",
    onSurface: "rgb(236, 224, 225)",
    surfaceVariant: "rgb(82, 67, 70)",
    onSurfaceVariant: "rgb(214, 194, 196)",
    outline: "rgb(158, 140, 143)",
    outlineVariant: "rgb(82, 67, 70)",
    shadow: "rgb(0, 0, 0)",
    scrim: "rgb(0, 0, 0)",
    inverseSurface: "rgb(236, 224, 225)",
    inverseOnSurface: "rgb(53, 47, 48)",
    inversePrimary: "rgb(187, 0, 85)",
    surfaceDisabled: "rgba(236, 224, 225, 0.12)",
    onSurfaceDisabled: "rgba(236, 224, 225, 0.38)",
    backdrop: "rgba(58, 45, 47, 0.4)",
    success: "rgb(73, 225, 124)",
    onSuccess: "rgb(0, 57, 23)",
    successContainer: "rgb(0, 82, 37)",
    onSuccessContainer: "rgb(106, 254, 150)",
  },
  elevation: {
    level0: "transparent",
    level1: "rgb(43, 34, 35)",
    level2: "rgb(50, 38, 40)",
    level3: "rgb(57, 43, 45)",
    level4: "rgb(59, 44, 47)",
    level5: "rgb(63, 47, 50)",
  },
  spacers,
  borderRadius,
  get tags() {
    return tags(this);
  },
};
