/* eslint-disable prettier/prettier */
export const DELAY_START = 0
export const DURATION_TRANSLATION_COMPONENT = 1000
export const DELAY_FIRST_ANIMATION = DELAY_START + 300
export const DURATION_FIRST_ANIMATION = 700

export const DELAY_ROTATION_AVATAR = DELAY_FIRST_ANIMATION + DURATION_FIRST_ANIMATION + 250
export const DURATION_FULL_ROTATION_AVATAR = 6000