export const DELAY_START_HEADER = 750;
export const DURATION_APPARITION_HEADER = 400;
export const DELAY_APPARITION_TEXT_HEADER = 250 + DELAY_START_HEADER;

export const DELAY_START_VINYL = DELAY_START_HEADER;
export const DURATION_TRANSLATION_COMPONENT = 1000;
export const DELAY_ROTATION_VINYL = DELAY_START_VINYL + 300;
export const DURATION_ROTATION_VINYL = 700;
export const DELAY_ROTATION_TONEARM = DELAY_ROTATION_VINYL;
export const DURATION_ROTATION_TONEARM = DURATION_ROTATION_VINYL;

export const DELAY_ROTATION_AVATAR =
  DELAY_ROTATION_VINYL + DURATION_ROTATION_VINYL + 250;
export const DURATION_FULL_ROTATION_AVATAR = 6000;

export const START_POSITION_Y_FLOAT_ICON = 35;

// total duration animation all icon = 3600
export const DELAY_START_FIRST_HEART =
  DELAY_ROTATION_VINYL + DURATION_ROTATION_VINYL;
export const DELAY_START_FIRST_NOTE = DELAY_START_FIRST_HEART + 900;
export const DELAY_START_SECOND_HEART = DELAY_START_FIRST_NOTE + 900;
export const DELAY_START_SECOND_NOTE = DELAY_START_SECOND_HEART + 900;

export const DURATION_FLOAT_ICON = 3000;
export const DELAY_OUT_FLOAT_ICON = 600;

export const DURATION_APPARITION_ICON = 500;

export const DELAY_BEFORE_REAPPARITION_FLOAT_ICON = 3100;

export const DELAY_APPARITION_BUTTONS =
  DELAY_ROTATION_VINYL + DURATION_ROTATION_VINYL + 500;
