name: CI Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Lint
        run: yarn lint

      - name: Check Formatting
        run: yarn format

      - name: Check Ts
        run: yarn typecheck
