name: CI Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Check Formatting
        run: npm run format-check

      - name: Build Swagger Beans
        run : npm run swagger:backend:update

      - name: Check Ts
        run: npm run typecheck
